# fly.toml app configuration file generated for mikesprojcos720-v1-spring-pond-2835 on 2024-04-20T12:46:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mikesprojcos720-v1-spring-pond-2835'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  ports = []

[[services]]
  protocol = 'tcp'
  internal_port = 8081
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          Access-Control-Allow-Headers = '*'
          Access-Control-Allow-Methods = '*'
          Access-Control-Allow-Origin = '*'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
